### ISSUE TITLE
Add error handling beyond general failure of a method

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/portal-unit-test#3]
Currently when an error occurs Python responds with a general error like:
```shell
======================================================================
ERROR: test_iterate_secrets_pages (__main__.PortalBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slate-portal/slate-portal/portal-unit-test/main.py", line 193, in test_iterate_secrets_pages
    helpers.delete_secret(
  File "/home/runner/work/slate-portal/slate-portal/portal-unit-test/main.py", line 957, in delete_secret
    self.__testcase.assertEqual(created_secret, created_secret_link.text)
AttributeError: 'NoneType' object has no attribute 'text'
----------------------------------------------------------------------
Ran 17 tests in 161.402s
```
This is unhelpful when trying to figure out what went wrong. Add more specific error handling where necessary.

**Comment by adamhgriffith-uofu** [comment]
This is related to https://github.com/slateci/slateci-unit-tests/issues/9.

**Comment by adamhgriffith-uofu** [comment]
For now just adding messages around valid page asserts.
