### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath'

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/portal-unit-test#9]
During a recent [GitHub Action](https://github.com/slateci/slate-portal/actions/runs/4176523104/jobs/7232915792) the following error was generated.
```shell
 ======================================================================
ERROR: test_iterate_secrets_pages (__main__.PortalBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slate-portal/slate-portal/portal-unit-test/main.py", line 166, in test_iterate_secrets_pages
    secrets_links = secrets_page.get_secret_links_on_cur_page()
  File "/home/runner/work/slate-portal/slate-portal/portal-unit-test/page.py", line 287, in get_secret_links_on_cur_page
    secrets_links = self.driver.find_elements_by_xpath("//td[@class='sorting_1']/a[1]")
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath'

----------------------------------------------------------------------
```

**Comment by adamhgriffith-uofu** [comment]
Adding @polinaLyubavina as a watcher.
